version: '3'
services:
  container:
    image: digitalsleuth/aurora:latest
    hostname: aurora
    container_name: aurora
    networks:
      net:
        ipv4_address: 172.23.0.3
    volumes:
      - ./files:/home/aurora/files/:ro
    ports:
      - "33:22"
    cap_add:
      - SYS_ADMIN
      - MKNOD
    privileged: true
    shm_size: "2gb"
    devices:
      - "/dev/fuse:/dev/fuse"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
